### ISSUE TITLE
ENHANCEMENT : Required UI Design for Home Page

### ISSUE THREAD

**Issue by SSameer20** [SSameer20/airselo#5]
### **Description**
Need  a clear and beautiful UI design for our project where design should make user a good experience

**Comment by MuskanSingh9934** [comment]
Assign me I can help you in designing UI

**Comment by SSameer20** [comment]
Assigned task #5 to @MuskanSingh9934

**Comment by SSameer20** [comment]
Contributed by `@MuskanSingh9934 `
